server.port: 8081
server.error.include-message: always
server.error.include-stacktrace: never
students.uri: http://localhost:8080/


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7777/realms/master
          jwk-set-uri: http://localhost:7777/realms/master/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://grades_pg:5432/grades
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
---
spring.config.activate.on-profile: docker
server.port: 8080
spring:
  devtools:
    livereload:
      enabled: true
